M48
; DRILL file {KiCad 9.0.4} date 2026-04-13T15:36:15-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-13T15:36:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X4.6176Y-4.3066
X4.6176Y-4.5342
T2
X4.5276Y-4.8819
X4.5669Y-2.1654
X7.3228Y-4.8819
M30
