M48
; DRILL file {KiCad 9.0.4} date 2026-03-13T05:34:26-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-13T05:34:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X5.0Y-4.2066
X5.0Y-4.4342
T2
X4.7638Y-2.185
X5.4134Y-4.8622
X7.1063Y-4.8622
M30
